export const mockPosts = [
  {
    id: 1,
    category: 'notice',
    labelText: '공지',
    title: '2026년 상반기 마케팅 전략 공유 세션 안내',
    content: '2026년 상반기 마케팅 전략 주요 세션을 다음과 같이 진행합니다. 주요 전략 방향과 실행 계획에 대해...',
    author: '이지현',
    team: '마케팅팀',
    date: '2026.05.14 10:25',
    views: 12,
    comments: 2,
    isMy: false,
    isImportant: false,
    moveBtn: '바로확인'
  },
  {
    id: 2,
    category: 'memo',
    labelText: '회람',
    title: '근무시간 변경 안내 (하계 유연근무제 시행)',
    content: '하계 유연근무제 시행에 따라 근무시간이 변경됩니다. 자세한 내용은 첨부 파일을 확인해 주세요.',
    author: '이준호',
    team: '인사팀',
    date: '2026.03.20 08:15',
    views: 5,
    comments: 0,
    isMy: true,
    isImportant: true,
    moveBtn: '확인하기'
  },
  {
    id: 3,
    category: 'announcement',
    labelText: '알림',
    title: '사내 카페 신규 메뉴 투표 이벤트 진행 안내',
    content: '사내 카페에서 새롭게 도입할 메뉴를 선정하기 위해 투표 이벤트를 진행합니다. 많은 참여 부탁드립니다.',
    author: '박서연',
    team: '총무팀',
    date: '2026.04.08 16:42',
    views: 3,
    comments: 0,
    isMy: false,
    isImportant: false,
    moveBtn: '바로확인'
  },
    { 
    id: 4,
    category: 'share',
    labelText: '공유',
    title: '업무 효율을 높여주는 AI 도구 활용 가이드',
    content: '업무에 반복 작업을 줄이는 AI 도구 활용 가이드를 공유드립니다.',
    author: '문서진',
    team: 'DX혁신팀',
    date: '2026.03.27 15:20',
    views: 6,
    comments: 1,
    isMy: false,
    isImportant: true,
    moveBtn: '바로확인'
    },
    { 
    id: 5,
    category: 'memo',
    labelText: '회람',
    title: '사무실 냉난방 기기 구매 요청 회람',
    content: '하반기 사무실 냉난방 기기 구매 목록을 검토해 주시고 회람 부탁드립니다.',
    author: '최문영',
    team: '경영지원팀',
    date: '2026.07.12 10:27',
    views: 2,
    comments: 3,
    isMy: false,
    isImportant: true,
    moveBtn: '확인하기'
    },
    { 
    id: 6,
    category: 'announcement',
    labelText: '알림',
    title: '팀워크 향상 프로그램 참가자 모집',
    content: '더 나은 협업을 위한 팀워크 향상 프로그램 참가자를 모집합니다.',
    author: '김대호',
    team: '조직문화팀',
    date: '2026.04.22 09:30',
    views: 4,
    comments: 0,
    isMy: true,
    isImportant: true,
    moveBtn: '바로확인'
    },
    { 
    id: 7,
    category: 'notice',
    labelText: '공지',
    title: '정보보안 교육 필수 이수 안내',
    content: '전 임직원 대상 정보보안 교육이 진행됩니다. 기한 내 필수 이수 부탁드립니다.',
    author: '정민준',
    team: '보안팀',
    date: '2026.06.03 11:00',
    views: 7,
    comments: 1,
    isMy: false,
    isImportant: false,
    moveBtn: '바로확인'
    },
    {
    id: 8,
    category: 'notice',
    labelText: '공지',
    title: '정보보안 교육 필수 이수 안내',
    content: '전 임직원 대상 정보보안 교육이 진행됩니다. 기한 내 필수 이수 부탁드립니다.',
    author: '정민준',
    team: '보안팀',
    date: '2026.06.03 11:00',
    views: 7,
    comments: 1,
    isMy: false,
    isImportant: false,
    moveBtn: '바로확인'
    },
];